version: '3.8'

services:
  # 1. De Go Ingestion Service
  ingestion:
    build: ./ingestion-service
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis:6379

  # 2. De Java Spring Boot API
  backend:
    build: ./backend-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/crypto_db
      - CORS_ALLOWED_ORIGINS=http://frontend:80
      - SPRING_DATA_REDIS_HOST=redis
      - CRYPTO_COOLDOWN_SECONDS=10

  # 3. De React Frontend
  frontend:
    build: ./frontend
    ports:
      - "5173:80" # We mappen poort 80 van Nginx naar poort 5173 op je pc
    depends_on:
      - backend

  # 4. Redis Broker
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # 5. PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=crypto_user
      - POSTGRES_PASSWORD=supergeheim
      - POSTGRES_DB=crypto_db
    ports:
      - "5433:5432"