version: '3.8'

services:
  # Go-service
  ingestion:
    build: ./ingestion-service
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis:6379

  # Redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # Database
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=crypto_user
      - POSTGRES_PASSWORD=supergeheim
      - POSTGRES_DB=crypto_db
    ports:
      - "5433:5432"