spring.data.redis.host=localhost
spring.data.redis.port=6379

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5433/crypto_db
spring.datasource.username=crypto_user
spring.datasource.password=supergeheim

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false