spring.data.redis.host=redis
spring.data.redis.port=6379

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://postgres:5432/crypto_db
spring.datasource.username=crypto_user
spring.datasource.password=supergeheim

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false